## create a special "vector" for cacheSolve 
## providing the caching interfaces for obtaining the inverse of a matrix x
makeCacheMatrix <- function(x= matrix()) {
  inv <- NULL
  set <- function(y) {
    x <<- y
    inv <<- NULL
  }
  get <- function() x
  setinv <- function(inverse) inv <<- inverse
  getinv <- function() inv
  
  list(set = set, get = get, setinv = setinv, getinv=getinv)
}


## Get the inverse of x in the format 
## of a special vector generated by makeCacheMatrix function 
## through cache if cache is available, 
## through calculation if no cache is available

cacheSolve <- function(x, ...) {
        inv <- x$getinv()
        if(!is.null(inv)){
          message("getting cached data")
          return(inv)
        }
        data <- x$get()
        inv <- solve(data);
        x$setinv(inv)
        inv
}
